[workspace]
members = [
    "neems-core",      # Your main package (renamed from src/)
    "crates/fixphrase"  # Your new fixphrase crate
]
resolver = "2"  # Recommended for Rust 2021+ editions

[workspace.dependencies]
diesel = { version = "2.1.0", features = ["sqlite"] }
diesel_migrations = "2.1.0"
dotenvy = "0.15"  # For loading .env files
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
