[package]
name = "neems-admin"
version = "0.1.0"
edition = "2024"

[dependencies]
neems-core = { path = "../neems-core" }
clap = { workspace = true, features = ["derive"] }
regex = { workspace = true }
rpassword = { workspace = true }
diesel = { workspace = true }
argon2 = { workspace = true }
dotenvy = { workspace = true }
chrono = { workspace = true }