[package]
name = "neems-core"
version = "0.1.0"
edition = "2024"

[dependencies]
fixphrase = { path = "../crates/fixphrase" }  

diesel.workspace = true
diesel_migrations.workspace = true
dotenvy.workspace = true
rocket.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
rocket = { version = "0.5.0", features = ["json"] }
serde_json = "1.0"