//! SLD presentation metadata for alarms (operator message + target SLD
//! objects).
//!
//! @generated by docs/alarms/build_alarm_meta_rs.py from
//! docs/alarms/newtown-alarms.json — DO NOT EDIT BY HAND. Regenerate after
//! changing the source spreadsheet/spec.
//!
//! `message` is the operator-facing mouseover text from the spreadsheet (empty
//! when the spreadsheet left it blank). `sld_targets` are the raw "Related SLD
//! Object" tokens; mapping them to concrete UI elements is the frontend's job,
//! so this module stays UI-agnostic.

/// Per-alarm SLD presentation metadata, keyed by `alarm_num`.
pub struct AlarmSldMeta {
    /// Unique alarm number (matches `AlarmDefinition::alarm_num`).
    pub alarm_num: u16,
    /// Operator-facing message; empty string when the spreadsheet had none.
    pub message: &'static str,
    /// Raw "Related SLD Object" tokens (e.g. `"Net"`, `"Border"`,
    /// `"52-MAIN-1"`).
    pub sld_targets: &'static [&'static str],
}

impl AlarmSldMeta {
    /// The message as an `Option`, treating the empty string as "no message".
    pub fn message_opt(&self) -> Option<&'static str> {
        if self.message.is_empty() {
            None
        } else {
            Some(self.message)
        }
    }
}

/// Look up SLD metadata for an alarm number.
pub fn sld_meta_for(alarm_num: u16) -> Option<&'static AlarmSldMeta> {
    ALARM_SLD_META.iter().find(|m| m.alarm_num == alarm_num)
}

/// SLD metadata for every digital alarm, in alarm-number order.
pub const ALARM_SLD_META: &[AlarmSldMeta] = &[
    AlarmSldMeta {
        alarm_num: 1,
        message: "Network communications: fiber, LTE service, cybersecurity, networking",
        sld_targets: &["Net"],
    },
    AlarmSldMeta {
        alarm_num: 2,
        message: "Network communications: fiber, LTE service, cybersecurity, networking",
        sld_targets: &["Net"],
    },
    AlarmSldMeta {
        alarm_num: 3,
        message: "Network communications: fiber, LTE service, cybersecurity, networking",
        sld_targets: &["Net", "Border"],
    },
    AlarmSldMeta {
        alarm_num: 4,
        message: "Network communications: fiber, LTE service, cybersecurity, networking",
        sld_targets: &["Net", "Border"],
    },
    AlarmSldMeta {
        alarm_num: 5,
        message: "Network communications: fiber, LTE service, cybersecurity, networking",
        sld_targets: &["Net"],
    },
    AlarmSldMeta {
        alarm_num: 6,
        message: "Network communications: fiber, LTE service, cybersecurity, networking",
        sld_targets: &["Net"],
    },
    AlarmSldMeta {
        alarm_num: 7,
        message: "Network communications: fiber, LTE service, cybersecurity, networking",
        sld_targets: &["Net"],
    },
    AlarmSldMeta {
        alarm_num: 8,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 9,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 10,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 11,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 12,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 13,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 14,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 15,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 101,
        message: "89L1 Open",
        sld_targets: &["52-MAIN-1"],
    },
    AlarmSldMeta {
        alarm_num: 102,
        message: "89L12 Open",
        sld_targets: &["52-MAIN-2"],
    },
    AlarmSldMeta {
        alarm_num: 103,
        message: "Lockout relay tripped - major site fault",
        sld_targets: &["LOR", "Border"],
    },
    AlarmSldMeta {
        alarm_num: 104,
        message: "Estop tripped",
        sld_targets: &["Estop", "Border"],
    },
    AlarmSldMeta {
        alarm_num: 105,
        message: "Loss relay",
        sld_targets: &["Relay", "Border"],
    },
    AlarmSldMeta {
        alarm_num: 106,
        message: "Loss relay",
        sld_targets: &["Relay", "Border"],
    },
    AlarmSldMeta {
        alarm_num: 107,
        message: "Relay protective function tripped disconnects",
        sld_targets: &["Relay"],
    },
    AlarmSldMeta {
        alarm_num: 108,
        message: "Relay protective function tripped disconnects",
        sld_targets: &["Relay"],
    },
    AlarmSldMeta {
        alarm_num: 109,
        message: "Relay protective function tripped disconnects",
        sld_targets: &["Relay"],
    },
    AlarmSldMeta {
        alarm_num: 110,
        message: "Relay protective function tripped disconnects",
        sld_targets: &["Relay"],
    },
    AlarmSldMeta {
        alarm_num: 111,
        message: "Relay protective function tripped disconnects",
        sld_targets: &["Relay"],
    },
    AlarmSldMeta {
        alarm_num: 112,
        message: "Relay protective function tripped disconnects",
        sld_targets: &["Relay"],
    },
    AlarmSldMeta {
        alarm_num: 113,
        message: "Relay protective function tripped disconnects",
        sld_targets: &["Relay"],
    },
    AlarmSldMeta {
        alarm_num: 114,
        message: "Relay protective function tripped disconnects",
        sld_targets: &["Relay"],
    },
    AlarmSldMeta {
        alarm_num: 115,
        message: "Relay protective function tripped disconnects",
        sld_targets: &["Relay"],
    },
    AlarmSldMeta {
        alarm_num: 116,
        message: "Relay protective function tripped disconnects",
        sld_targets: &["Relay"],
    },
    AlarmSldMeta {
        alarm_num: 117,
        message: "Relay protective function tripped disconnects",
        sld_targets: &["Relay"],
    },
    AlarmSldMeta {
        alarm_num: 118,
        message: "Relay protective function tripped disconnects",
        sld_targets: &["Relay"],
    },
    AlarmSldMeta {
        alarm_num: 119,
        message: "Relay protective function tripped disconnects",
        sld_targets: &["Relay"],
    },
    AlarmSldMeta {
        alarm_num: 120,
        message: "Relay protective function tripped disconnects",
        sld_targets: &["Relay"],
    },
    AlarmSldMeta {
        alarm_num: 121,
        message: "Relay protective function tripped disconnects",
        sld_targets: &["Relay"],
    },
    AlarmSldMeta {
        alarm_num: 122,
        message: "Relay protective function tripped disconnects",
        sld_targets: &["Relay"],
    },
    AlarmSldMeta {
        alarm_num: 123,
        message: "Relay protective function tripped disconnects",
        sld_targets: &["Relay"],
    },
    AlarmSldMeta {
        alarm_num: 124,
        message: "Relay protective function tripped disconnects",
        sld_targets: &["Relay"],
    },
    AlarmSldMeta {
        alarm_num: 125,
        message: "Relay protective function tripped disconnects",
        sld_targets: &["Relay"],
    },
    AlarmSldMeta {
        alarm_num: 126,
        message: "Relay protective function tripped disconnects",
        sld_targets: &["Relay"],
    },
    AlarmSldMeta {
        alarm_num: 127,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 128,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 129,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 130,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 131,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 132,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 133,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 134,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 135,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 201,
        message: "POI Meter unavailable",
        sld_targets: &["Meter"],
    },
    AlarmSldMeta {
        alarm_num: 202,
        message: "POI Meter unavailable",
        sld_targets: &["Meter"],
    },
    AlarmSldMeta {
        alarm_num: 203,
        message: "POI Meter unavailable",
        sld_targets: &["Meter"],
    },
    AlarmSldMeta {
        alarm_num: 204,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 205,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 206,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 207,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 208,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 209,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 210,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 301,
        message: "",
        sld_targets: &["T1"],
    },
    AlarmSldMeta {
        alarm_num: 302,
        message: "",
        sld_targets: &["T1"],
    },
    AlarmSldMeta {
        alarm_num: 303,
        message: "Trouble",
        sld_targets: &["T1"],
    },
    AlarmSldMeta {
        alarm_num: 304,
        message: "",
        sld_targets: &["T1"],
    },
    AlarmSldMeta {
        alarm_num: 305,
        message: "",
        sld_targets: &["T1"],
    },
    AlarmSldMeta {
        alarm_num: 306,
        message: "",
        sld_targets: &["T1"],
    },
    AlarmSldMeta {
        alarm_num: 307,
        message: "",
        sld_targets: &["T1"],
    },
    AlarmSldMeta {
        alarm_num: 308,
        message: "",
        sld_targets: &["T1"],
    },
    AlarmSldMeta {
        alarm_num: 309,
        message: "",
        sld_targets: &["T1"],
    },
    AlarmSldMeta {
        alarm_num: 310,
        message: "",
        sld_targets: &["T1"],
    },
    AlarmSldMeta {
        alarm_num: 311,
        message: "",
        sld_targets: &["T2"],
    },
    AlarmSldMeta {
        alarm_num: 312,
        message: "",
        sld_targets: &["T2"],
    },
    AlarmSldMeta {
        alarm_num: 313,
        message: "Trouble",
        sld_targets: &["T2"],
    },
    AlarmSldMeta {
        alarm_num: 314,
        message: "",
        sld_targets: &["T2"],
    },
    AlarmSldMeta {
        alarm_num: 315,
        message: "",
        sld_targets: &["T2"],
    },
    AlarmSldMeta {
        alarm_num: 316,
        message: "",
        sld_targets: &["T2"],
    },
    AlarmSldMeta {
        alarm_num: 317,
        message: "",
        sld_targets: &["T2"],
    },
    AlarmSldMeta {
        alarm_num: 318,
        message: "",
        sld_targets: &["T2"],
    },
    AlarmSldMeta {
        alarm_num: 319,
        message: "",
        sld_targets: &["T2"],
    },
    AlarmSldMeta {
        alarm_num: 320,
        message: "",
        sld_targets: &["T2"],
    },
    AlarmSldMeta {
        alarm_num: 321,
        message: "",
        sld_targets: &["CE_SCADA"],
    },
    AlarmSldMeta {
        alarm_num: 322,
        message: "Loss of utility AC",
        sld_targets: &["SST-UPS"],
    },
    AlarmSldMeta {
        alarm_num: 323,
        message: "Low UPS DC power",
        sld_targets: &["SST-UPS"],
    },
    AlarmSldMeta {
        alarm_num: 324,
        message: "Trouble",
        sld_targets: &["SST-UPS"],
    },
    AlarmSldMeta {
        alarm_num: 325,
        message: "Trouble",
        sld_targets: &["SST-UPS"],
    },
    AlarmSldMeta {
        alarm_num: 326,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 327,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 328,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 329,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 330,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 401,
        message: "FIRE!!",
        sld_targets: &["FACP"],
    },
    AlarmSldMeta {
        alarm_num: 402,
        message: "Trouble",
        sld_targets: &["FACP"],
    },
    AlarmSldMeta {
        alarm_num: 403,
        message: "Supervisory",
        sld_targets: &["FACP"],
    },
    AlarmSldMeta {
        alarm_num: 404,
        message: "FIRE!!",
        sld_targets: &["FACP"],
    },
    AlarmSldMeta {
        alarm_num: 405,
        message: "FIRE!!",
        sld_targets: &["FACP"],
    },
    AlarmSldMeta {
        alarm_num: 406,
        message: "FIRE!!",
        sld_targets: &["FACP"],
    },
    AlarmSldMeta {
        alarm_num: 407,
        message: "FIRE!!",
        sld_targets: &["FACP"],
    },
    AlarmSldMeta {
        alarm_num: 408,
        message: "FIRE!!",
        sld_targets: &["FACP"],
    },
    AlarmSldMeta {
        alarm_num: 409,
        message: "FIRE!!",
        sld_targets: &["FACP"],
    },
    AlarmSldMeta {
        alarm_num: 410,
        message: "FIRE!!",
        sld_targets: &["FACP"],
    },
    AlarmSldMeta {
        alarm_num: 411,
        message: "FIRE!!",
        sld_targets: &["FACP"],
    },
    AlarmSldMeta {
        alarm_num: 412,
        message: "FIRE!!",
        sld_targets: &["FACP"],
    },
    AlarmSldMeta {
        alarm_num: 413,
        message: "FIRE!!",
        sld_targets: &["FACP"],
    },
    AlarmSldMeta {
        alarm_num: 414,
        message: "Deluge active",
        sld_targets: &["FACP"],
    },
    AlarmSldMeta {
        alarm_num: 415,
        message: "Deluge active",
        sld_targets: &["FACP"],
    },
    AlarmSldMeta {
        alarm_num: 416,
        message: "Deluge active",
        sld_targets: &["FACP"],
    },
    AlarmSldMeta {
        alarm_num: 417,
        message: "Deluge active",
        sld_targets: &["FACP"],
    },
    AlarmSldMeta {
        alarm_num: 418,
        message: "Deluge active",
        sld_targets: &["FACP"],
    },
    AlarmSldMeta {
        alarm_num: 419,
        message: "",
        sld_targets: &["MP1A"],
    },
    AlarmSldMeta {
        alarm_num: 420,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 421,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 422,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 423,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 424,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 425,
        message: "",
        sld_targets: &[],
    },
    AlarmSldMeta {
        alarm_num: 501,
        message: "Meter trouble",
        sld_targets: &["M1"],
    },
    AlarmSldMeta {
        alarm_num: 502,
        message: "Meter trouble",
        sld_targets: &["M1"],
    },
    AlarmSldMeta {
        alarm_num: 503,
        message: "Meter trouble",
        sld_targets: &["M1"],
    },
    AlarmSldMeta {
        alarm_num: 504,
        message: "Meter trouble",
        sld_targets: &["M1"],
    },
    AlarmSldMeta {
        alarm_num: 505,
        message: "Meter trouble",
        sld_targets: &["M1"],
    },
    AlarmSldMeta {
        alarm_num: 506,
        message: "Meter trouble",
        sld_targets: &["M2"],
    },
    AlarmSldMeta {
        alarm_num: 507,
        message: "Meter trouble",
        sld_targets: &["M2"],
    },
    AlarmSldMeta {
        alarm_num: 508,
        message: "Meter trouble",
        sld_targets: &["M2"],
    },
    AlarmSldMeta {
        alarm_num: 509,
        message: "Meter trouble",
        sld_targets: &["M2"],
    },
    AlarmSldMeta {
        alarm_num: 510,
        message: "Meter trouble",
        sld_targets: &["M2"],
    },
    AlarmSldMeta {
        alarm_num: 601,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 602,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 603,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 604,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 605,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 606,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 607,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 608,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 609,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 610,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 611,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 612,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 613,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 614,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 615,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 616,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 617,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 618,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 619,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 620,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 621,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 622,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 623,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 624,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 625,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 626,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 627,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 628,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 629,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 630,
        message: "",
        sld_targets: &["MP-1A"],
    },
    AlarmSldMeta {
        alarm_num: 631,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 632,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 633,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 634,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 635,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 636,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 637,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 638,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 639,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 640,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 641,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 642,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 643,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 644,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 645,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 646,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 647,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 648,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 649,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 650,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 651,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 652,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 653,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 654,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 655,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 656,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 657,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 658,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 659,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 660,
        message: "",
        sld_targets: &["MP-1B"],
    },
    AlarmSldMeta {
        alarm_num: 661,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 662,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 663,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 664,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 665,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 666,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 667,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 668,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 669,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 670,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 671,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 672,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 673,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 674,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 675,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 676,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 677,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 678,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 679,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 680,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 681,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 682,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 683,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 684,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 685,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 686,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 687,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 688,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 689,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 690,
        message: "",
        sld_targets: &["MP-1C"],
    },
    AlarmSldMeta {
        alarm_num: 691,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 692,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 693,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 694,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 695,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 696,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 697,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 698,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 699,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 700,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 701,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 702,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 703,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 704,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 705,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 706,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 707,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 708,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 709,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 710,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 711,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 712,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 713,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 714,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 715,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 716,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 717,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 718,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 719,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 720,
        message: "",
        sld_targets: &["MP-2A"],
    },
    AlarmSldMeta {
        alarm_num: 721,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 722,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 723,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 724,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 725,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 726,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 727,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 728,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 729,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 730,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 731,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 732,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 733,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 734,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 735,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 736,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 737,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 738,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 739,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 740,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 741,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 742,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 743,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 744,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 745,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 746,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 747,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 748,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 749,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 750,
        message: "",
        sld_targets: &["MP-2B"],
    },
    AlarmSldMeta {
        alarm_num: 751,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 752,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 753,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 754,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 755,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 756,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 757,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 758,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 759,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 760,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 761,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 762,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 763,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 764,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 765,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 766,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 767,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 768,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 769,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 770,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 771,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 772,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 773,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 774,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 775,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 776,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 777,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 778,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 779,
        message: "",
        sld_targets: &["MP-2C"],
    },
    AlarmSldMeta {
        alarm_num: 780,
        message: "",
        sld_targets: &["MP-2C"],
    },
];
