#!/usr/bin/env python3
"""Generate the Rust alarm SLD-metadata module from the alarm spec.

Emits one site design's ``ALARM_SLD_META`` table — for Newtown,
``neems-data/src/rtac/design/newtown/alarm_sld_meta.rs`` — a per-alarm table of the
operator-facing message (spreadsheet "Mouseover") and the target SLD object
tokens (spreadsheet "Related SLD Object"), keyed by alarm_num. This keeps the
spreadsheet/spec as the single source of truth: the data flows
spreadsheet -> newtown-alarms.json -> this generated module -> API DTOs ->
generated TypeScript types -> frontend.

Run (after regenerating newtown-alarms.json):

    python3 neems-core/docs/alarms/build_alarm_meta_rs.py

The defaults are Newtown's spec and design module; pass ``--spec`` and
``--out`` to generate another design's table.

The output is emitted in rustfmt's layout (matching the workspace rustfmt.toml),
so regenerating round-trips with no diff and no separate `cargo fmt` step. If the
formatting config ever changes, run `cargo fmt` once and copy the resulting
header back into HEADER below.

The mapping of tokens to concrete UI elements is intentionally NOT done here;
that is the frontend's responsibility (the backend stays UI-agnostic).
"""

import argparse
import json
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
SPEC = SCRIPT_DIR / "newtown-alarms.json"
# neems-core/docs/alarms -> neems-core
NEEMS_CORE = SCRIPT_DIR.parents[1]
OUT = NEEMS_CORE / "neems-data" / "src" / "rtac" / "design" / "newtown" / "alarm_sld_meta.rs"


def rust_str(s: str) -> str:
    """Escape a Python string as a Rust double-quoted string literal."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def rust_targets(tokens) -> str:
    if not tokens:
        return "&[]"
    return "&[" + ", ".join(rust_str(t) for t in tokens) + "]"


HEADER = """\
//! SLD presentation metadata for this design's alarms. See
//! [`crate::rtac::alarm_sld_meta`] for what the fields mean.
//!
//! @generated by docs/alarms/build_alarm_meta_rs.py from
//! {spec} — DO NOT EDIT BY HAND. Regenerate after
//! changing the source spreadsheet/spec.

use crate::rtac::alarm_sld_meta::AlarmSldMeta;

/// SLD metadata for every digital alarm, in alarm-number order.
pub const ALARM_SLD_META: &[AlarmSldMeta] = &[
"""


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--spec",
        type=Path,
        default=SPEC,
        help=f"alarm spec JSON to read (default: {SPEC.relative_to(NEEMS_CORE)})",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=OUT,
        help=f"Rust module to write (default: {OUT.relative_to(NEEMS_CORE)})",
    )
    return parser.parse_args()


def spec_label(spec: Path) -> str:
    """The spec's path as the generated header names it: repo-relative when it
    is inside neems-core, so regenerating on another machine does not churn."""
    try:
        return str(spec.resolve().relative_to(NEEMS_CORE))
    except ValueError:
        return spec.name


def main():
    args = parse_args()
    spec = json.loads(args.spec.read_text())
    rows = []
    # Sorted, not spreadsheet order: the table below documents itself as being
    # in alarm-number order, and a row the client appends out of sequence
    # (PSV05T, added below the reserved block) would otherwise land in the
    # middle of nowhere and make the next diff unreadable.
    for e in sorted(spec["digital_alarms"], key=lambda e: e["alarm_num"]):
        msg = e.get("mouseover") or ""
        targets = e["sld"]["related_objects"]
        # Emit the rustfmt layout directly so regenerating round-trips cleanly
        # (no `cargo fmt` step needed and no spurious diff). Verified that no
        # line exceeds rustfmt's width, so this matches its output exactly.
        rows.append(
            "    AlarmSldMeta {\n"
            f"        alarm_num: {e['alarm_num']},\n"
            f"        message: {rust_str(msg)},\n"
            f"        sld_targets: {rust_targets(targets)},\n"
            "    },"
        )
    body = HEADER.replace("{spec}", spec_label(args.spec)) + "\n".join(rows) + "\n];\n"
    args.out.write_text(body)
    n_msg = sum(1 for e in spec["digital_alarms"] if e.get("mouseover"))
    n_tgt = sum(1 for e in spec["digital_alarms"] if e["sld"]["related_objects"])
    print(f"wrote {args.out}")
    print(f"  {len(rows)} alarms ({n_msg} with message, {n_tgt} with targets)")


if __name__ == "__main__":
    main()
