#!/usr/bin/env python3
"""Generate the Rust analog-point registry from the alarm spec.

Emits one site design's analog tables — for Newtown,
``neems-data/src/rtac/design/newtown/analog_points.rs`` — every analog point on the
spreadsheet's ``Analogs`` sheet, keyed by its point number. The point number is
the point's Modbus register address on the RTAC, so this table is the register
map for the analog side, not just documentation.

Run (after regenerating newtown-alarms.json):

    python3 neems-core/docs/alarms/build_analog_points_rs.py

The defaults are Newtown's spec and design module; pass ``--spec`` and
``--out`` to generate another design's tables.

The output is emitted in rustfmt's layout (matching the workspace
rustfmt.toml), so regenerating round-trips with no diff and no separate
`cargo fmt` step.

Units and scaling are deliberately NOT emitted. The spreadsheet gives neither
for any analog row, and inventing an encoding here would put a plausible but
wrong number on an operator's gauge. Scaling lives in `protocol.rs` for the
three points whose encoding we have a basis for; everything else is carried
raw.
"""

import argparse
import json
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
SPEC = SCRIPT_DIR / "newtown-alarms.json"
# neems-core/docs/alarms -> neems-core
NEEMS_CORE = SCRIPT_DIR.parents[1]
OUT = NEEMS_CORE / "neems-data" / "src" / "rtac" / "design" / "newtown" / "analog_points.rs"


def rust_str(s: str) -> str:
    """Escape a Python string as a Rust double-quoted string literal."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


HEADER = '''\
//! This design's analog point registry: every measurement the client's
//! `Analogs` sheet defines. See [`crate::rtac::analog_points`] for what the
//! fields mean.
//!
//! @generated by docs/alarms/build_analog_points_rs.py from
//! {spec} — DO NOT EDIT BY HAND. Regenerate after
//! changing the source spreadsheet/spec.

use crate::rtac::{alarm_definitions::AlarmZone, analog_points::AnalogPoint};

/// The 30 per-Megapack measurement names, in block order, from MP-1A.
///
/// Every pack repeats this list, so it is captured once. MP-1A is the clean
/// copy: blocks 1B-2C label offset 14 `ac_voltage_phaseA` where MP-1A has
/// `inverter_phaseA_current`, which the spec flags as a copy/paste error.
pub const MEGAPACK_ANALOG_NAMES: [&str; MEGAPACK_ANALOG_NAME_COUNT] = [
{names}];

/// Length of [`MEGAPACK_ANALOG_NAMES`]; matches
/// [`MP_ANALOG_POINT_COUNT`][crate::rtac::protocol::MP_ANALOG_POINT_COUNT].
pub const MEGAPACK_ANALOG_NAME_COUNT: usize = {name_count};

/// Every analog point the client defines, in point-number order.
pub const ANALOG_POINTS: &[AnalogPoint] = &[
'''


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--spec",
        type=Path,
        default=SPEC,
        help=f"alarm spec JSON to read (default: {SPEC.relative_to(NEEMS_CORE)})",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=OUT,
        help=f"Rust module to write (default: {OUT.relative_to(NEEMS_CORE)})",
    )
    return parser.parse_args()


def spec_label(spec: Path) -> str:
    """The spec's path as the generated header names it: repo-relative when it
    is inside neems-core, so regenerating on another machine does not churn."""
    try:
        return str(spec.resolve().relative_to(NEEMS_CORE))
    except ValueError:
        return spec.name

# Spreadsheet zone label -> the Rust AlarmZone variant.
ZONE_VARIANT = {
    "Transformer1": "Transformer1",
    "Transformer2": "Transformer2",
    "Mp1a": "Mp1a",
    "Mp1b": "Mp1b",
    "Mp1c": "Mp1c",
    "Mp2a": "Mp2a",
    "Mp2b": "Mp2b",
    "Mp2c": "Mp2c",
}

# Point number of each Megapack block's first row, matching
# MEGAPACK_ANALOG_BASE_POINT in protocol.rs.
MP_BASE = {"Mp1a": 601, "Mp1b": 631, "Mp1c": 661, "Mp2a": 691, "Mp2b": 721, "Mp2c": 751}


def main():
    args = parse_args()
    spec = json.loads(args.spec.read_text())
    points = sorted(spec["analog_points"], key=lambda e: e["alarm_num"])

    # This registry describes read-only float measurements and nothing else:
    # the Rust table carries no encoding and the read path never writes. When
    # the client's writable sheet lands, its points must not fall silently into
    # a read-only registry, so refuse rather than emit them.
    for e in points:
        if e.get("value_type") != "float" or e.get("access") != "read_only":
            raise SystemExit(
                f"point {e['alarm_num']} is {e.get('value_type')}/{e.get('access')}, "
                "not float/read_only — this generator emits neither; decide where "
                "the point belongs before regenerating"
            )

    rows = []
    for e in points:
        zone = e["zone"]
        if zone not in ZONE_VARIANT:
            raise SystemExit(f"unmapped analog zone {zone!r} on point {e['alarm_num']}")
        base = MP_BASE.get(zone)
        offset = "None" if base is None else f"Some({e['alarm_num'] - base})"
        rows.append(
            "    AnalogPoint {\n"
            f"        point_number: {e['alarm_num']},\n"
            f"        zone: AlarmZone::{ZONE_VARIANT[zone]},\n"
            f"        name: {rust_str(e['name'])},\n"
            f"        offset: {offset},\n"
            f"        spare: {str(e['spare']).lower()},\n"
            f"        is_fire: {str(e['is_fire']).lower()},\n"
            "    },"
        )

    mp1a = [e for e in points if e["zone"] == "Mp1a"]
    names = "".join(f"    {rust_str(e['name'])},\n" for e in mp1a)
    header = (
        HEADER.replace("{spec}", spec_label(args.spec))
        .replace("{names}", names)
        .replace("{name_count}", str(len(mp1a)))
    )

    args.out.write_text(header + "\n".join(rows) + "\n];\n")
    n_spare = sum(1 for e in points if e["spare"])
    n_site = sum(1 for e in points if e["zone"] not in MP_BASE)
    print(f"wrote {args.out}")
    print(f"  {len(rows)} analog points ({n_spare} spare, {n_site} site-level)")


if __name__ == "__main__":
    main()
