#!/usr/bin/env python3
"""Generate the Rust alarm SLD-metadata module from the alarm spec.

Emits ``neems-data/src/rtac/alarm_sld_meta.rs`` — a per-alarm table of the
operator-facing message (spreadsheet "Mouseover") and the target SLD object
tokens (spreadsheet "Related SLD Object"), keyed by alarm_num. This keeps the
spreadsheet/spec as the single source of truth: the data flows
spreadsheet -> newtown-alarms.json -> this generated module -> API DTOs ->
generated TypeScript types -> frontend.

Run (after regenerating newtown-alarms.json):

    python3 neems-core/docs/alarms/build_alarm_meta_rs.py

The output is emitted in rustfmt's layout (matching the workspace rustfmt.toml),
so regenerating round-trips with no diff and no separate `cargo fmt` step. If the
formatting config ever changes, run `cargo fmt` once and copy the resulting
header back into HEADER below.

The mapping of tokens to concrete UI elements is intentionally NOT done here;
that is the frontend's responsibility (the backend stays UI-agnostic).
"""

import json
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
SPEC = SCRIPT_DIR / "newtown-alarms.json"
# neems-core/docs/alarms -> neems-core
NEEMS_CORE = SCRIPT_DIR.parents[1]
OUT = NEEMS_CORE / "neems-data" / "src" / "rtac" / "alarm_sld_meta.rs"


def rust_str(s: str) -> str:
    """Escape a Python string as a Rust double-quoted string literal."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def rust_targets(tokens) -> str:
    if not tokens:
        return "&[]"
    return "&[" + ", ".join(rust_str(t) for t in tokens) + "]"


HEADER = """\
//! SLD presentation metadata for alarms (operator message + target SLD
//! objects).
//!
//! @generated by docs/alarms/build_alarm_meta_rs.py from
//! docs/alarms/newtown-alarms.json — DO NOT EDIT BY HAND. Regenerate after
//! changing the source spreadsheet/spec.
//!
//! `message` is the operator-facing mouseover text from the spreadsheet (empty
//! when the spreadsheet left it blank). `sld_targets` are the raw "Related SLD
//! Object" tokens; mapping them to concrete UI elements is the frontend's job,
//! so this module stays UI-agnostic.

/// Per-alarm SLD presentation metadata, keyed by `alarm_num`.
pub struct AlarmSldMeta {
    /// Unique alarm number (matches `AlarmDefinition::alarm_num`).
    pub alarm_num: u16,
    /// Operator-facing message; empty string when the spreadsheet had none.
    pub message: &'static str,
    /// Raw "Related SLD Object" tokens (e.g. `"Net"`, `"Border"`,
    /// `"52-MAIN-1"`).
    pub sld_targets: &'static [&'static str],
}

impl AlarmSldMeta {
    /// The message as an `Option`, treating the empty string as "no message".
    pub fn message_opt(&self) -> Option<&'static str> {
        if self.message.is_empty() {
            None
        } else {
            Some(self.message)
        }
    }
}

/// Look up SLD metadata for an alarm number.
pub fn sld_meta_for(alarm_num: u16) -> Option<&'static AlarmSldMeta> {
    ALARM_SLD_META.iter().find(|m| m.alarm_num == alarm_num)
}

/// SLD metadata for every digital alarm, in alarm-number order.
pub const ALARM_SLD_META: &[AlarmSldMeta] = &[
"""


def main():
    spec = json.loads(SPEC.read_text())
    rows = []
    for e in spec["digital_alarms"]:
        msg = e.get("mouseover") or ""
        targets = e["sld"]["related_objects"]
        # Emit the rustfmt layout directly so regenerating round-trips cleanly
        # (no `cargo fmt` step needed and no spurious diff). Verified that no
        # line exceeds rustfmt's width, so this matches its output exactly.
        rows.append(
            "    AlarmSldMeta {\n"
            f"        alarm_num: {e['alarm_num']},\n"
            f"        message: {rust_str(msg)},\n"
            f"        sld_targets: {rust_targets(targets)},\n"
            "    },"
        )
    body = HEADER + "\n".join(rows) + "\n];\n"
    OUT.write_text(body)
    n_msg = sum(1 for e in spec["digital_alarms"] if e.get("mouseover"))
    n_tgt = sum(1 for e in spec["digital_alarms"] if e["sld"]["related_objects"])
    print(f"wrote {OUT}")
    print(f"  {len(rows)} alarms ({n_msg} with message, {n_tgt} with targets)")


if __name__ == "__main__":
    main()
