#!/usr/bin/env python3
"""Generate the Rust analog-point registry from the alarm spec.

Emits ``neems-data/src/rtac/analog_points.rs`` — every analog point on the
spreadsheet's ``Analogs`` sheet, keyed by its point number. The point number is
the point's Modbus register address on the RTAC, so this table is the register
map for the analog side, not just documentation.

Run (after regenerating newtown-alarms.json):

    python3 neems-core/docs/alarms/build_analog_points_rs.py

The output is emitted in rustfmt's layout (matching the workspace
rustfmt.toml), so regenerating round-trips with no diff and no separate
`cargo fmt` step.

Units and scaling are deliberately NOT emitted. The spreadsheet gives neither
for any analog row, and inventing an encoding here would put a plausible but
wrong number on an operator's gauge. Scaling lives in `protocol.rs` for the
three points whose encoding we have a basis for; everything else is carried
raw.
"""

import json
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
SPEC = SCRIPT_DIR / "newtown-alarms.json"
# neems-core/docs/alarms -> neems-core
NEEMS_CORE = SCRIPT_DIR.parents[1]
OUT = NEEMS_CORE / "neems-data" / "src" / "rtac" / "analog_points.rs"


def rust_str(s: str) -> str:
    """Escape a Python string as a Rust double-quoted string literal."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


HEADER = '''\
//! Analog point registry — every measurement the client's `Analogs` sheet
//! defines, with the Modbus address each is read from.
//!
//! @generated by docs/alarms/build_analog_points_rs.py from
//! docs/alarms/newtown-alarms.json — DO NOT EDIT BY HAND. Regenerate after
//! changing the source spreadsheet/spec.
//!
//! ## The point number is the address
//!
//! `point_number` is the spreadsheet's "alarm number" for the row, and it *is*
//! the point's Modbus register address (via
//! [`RegisterMap::point_address`][crate::rtac::protocol::RegisterMap::point_address],
//! which carries the one assumption about numbering base). A digital alarm of
//! the same zone shares the number — 601 is both MP-1A `real_power_target`
//! here and MP-1A `megapack_loss_of_comms` in
//! [`ALARM_DEFINITIONS`][crate::rtac::alarm_definitions::ALARM_DEFINITIONS] —
//! and they do not collide because Modbus addresses registers and bits
//! separately.
//!
//! ## No units, no scaling
//!
//! The spreadsheet gives neither for any row, so neither appears here. Only
//! the three points the SLD renders are decoded, and their scaling lives in
//! `protocol.rs` where the assumption is documented; every other point is
//! carried through as a raw register value rather than given an encoding we
//! would have to unpick later.

use super::alarm_definitions::AlarmZone;

/// One analog measurement from the client's `Analogs` sheet.
pub struct AnalogPoint {
    /// The spreadsheet's number for this row, which is also its Modbus
    /// register address. Unique among analog points, but shared with the
    /// digital alarm of the same number.
    pub point_number: u16,
    /// Zone the measurement belongs to.
    pub zone: AlarmZone,
    /// Name as written in the spreadsheet.
    pub name: &'static str,
    /// Position within the owning Megapack's 30-point block, or `None` for the
    /// two site-level transformer points that belong to no block.
    pub offset: Option<u16>,
    /// True for the `AI_spare_*` rows the client reserved but left undefined.
    pub spare: bool,
    /// The spreadsheet's "IsFire?" flag.
    pub is_fire: bool,
}

/// Look up an analog point by its number (equivalently, its address).
pub fn analog_point(point_number: u16) -> Option<&'static AnalogPoint> {
    ANALOG_POINTS.iter().find(|p| p.point_number == point_number)
}

/// Look up a Megapack point's name by its offset within a pack block.
pub fn megapack_point_name(offset: u16) -> Option<&'static str> {
    MEGAPACK_ANALOG_NAMES.get(offset as usize).copied()
}

/// The 30 per-Megapack measurement names, in block order, from MP-1A.
///
/// Every pack repeats this list, so it is captured once. MP-1A is the clean
/// copy: blocks 1B-2C label offset 14 `ac_voltage_phaseA` where MP-1A has
/// `inverter_phaseA_current`, which the spec flags as a copy/paste error.
pub const MEGAPACK_ANALOG_NAMES: [&str; MEGAPACK_ANALOG_NAME_COUNT] = [
{names}];

/// Length of [`MEGAPACK_ANALOG_NAMES`]; matches
/// [`MP_ANALOG_POINT_COUNT`][crate::rtac::protocol::MP_ANALOG_POINT_COUNT].
pub const MEGAPACK_ANALOG_NAME_COUNT: usize = {name_count};

/// Every analog point the client defines, in point-number order.
pub const ANALOG_POINTS: &[AnalogPoint] = &[
'''

# Spreadsheet zone label -> the Rust AlarmZone variant.
ZONE_VARIANT = {
    "Transformer1": "Transformer1",
    "Transformer2": "Transformer2",
    "Mp1a": "Mp1a",
    "Mp1b": "Mp1b",
    "Mp1c": "Mp1c",
    "Mp2a": "Mp2a",
    "Mp2b": "Mp2b",
    "Mp2c": "Mp2c",
}

# Point number of each Megapack block's first row, matching
# MEGAPACK_ANALOG_BASE_POINT in protocol.rs.
MP_BASE = {"Mp1a": 601, "Mp1b": 631, "Mp1c": 661, "Mp2a": 691, "Mp2b": 721, "Mp2c": 751}


def main():
    spec = json.loads(SPEC.read_text())
    points = sorted(spec["analog_points"], key=lambda e: e["alarm_num"])

    rows = []
    for e in points:
        zone = e["zone"]
        if zone not in ZONE_VARIANT:
            raise SystemExit(f"unmapped analog zone {zone!r} on point {e['alarm_num']}")
        base = MP_BASE.get(zone)
        offset = "None" if base is None else f"Some({e['alarm_num'] - base})"
        rows.append(
            "    AnalogPoint {\n"
            f"        point_number: {e['alarm_num']},\n"
            f"        zone: AlarmZone::{ZONE_VARIANT[zone]},\n"
            f"        name: {rust_str(e['name'])},\n"
            f"        offset: {offset},\n"
            f"        spare: {str(e['spare']).lower()},\n"
            f"        is_fire: {str(e['is_fire']).lower()},\n"
            "    },"
        )

    mp1a = [e for e in points if e["zone"] == "Mp1a"]
    names = "".join(f"    {rust_str(e['name'])},\n" for e in mp1a)
    header = HEADER.replace("{names}", names).replace("{name_count}", str(len(mp1a)))

    OUT.write_text(header + "\n".join(rows) + "\n];\n")
    n_spare = sum(1 for e in points if e["spare"])
    n_site = sum(1 for e in points if e["zone"] not in MP_BASE)
    print(f"wrote {OUT}")
    print(f"  {len(rows)} analog points ({n_spare} spare, {n_site} site-level)")


if __name__ == "__main__":
    main()
